name: CI - Tag

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  ci:
    permissions:
      contents: write
      security-events: write
      actions: read
      packages: write
      id-token: write
    uses: TourinhoM/org-ci-platform/.github/workflows/ci-tag.yml@main
    secrets: inherit
